name: Robo-Gilvan-Auto

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Rodar Script
        run: python main.py
      - name: Salvar no GitHub
        run: |
          git config --global user.name "Gilvan"
          git config --global user.email "gilvan@exemplo.com"
          git add .
          git commit -m "Update" || exit 0
          git push
